electric_grid_emissions_f <- function(fleet_elec_use_tot_county, share_ng_cons_elec = NA, fleet_electricity_consumption_source = NA, scenario_id = NA, electricity_EF_source = NA, last_yr = NA, electricity_EF_change_scenario = NA, fleet_id = NA, elec_ef_source = NA, emissions_multiplier_SO2 = NA, emissions_multiplier_NOx = NA, emissions_multiplier_PM25 = NA, dynamic_efs = NA, efs_convergence = NA, efs_yearly_change = NA, elec_mix_mdl = NA) {
  # Computes the regional emissions of pollutants generated by the electricity necessary to power battery electric vehicles. 
  attribute_f("electric_grid_emissions_f")
  results_path <- paste0(getwd(), "/outputs/air_quality/", Sys.Date(), "_", scenario_id, "_results")
  first_proj_yr <- 2022
  GIS_matching_matrix <- read.csv(paste0(getwd(), "/inputs/air_quality/GIS_matching_matrix.csv"))
    
  ## Calculate the background electricity use = the electricity not used to power BEVs
  US_elec_use <- read.table(paste0(getwd(), "/inputs/air_quality/", "2023AEO_Electricity_Use.csv"), check.names = FALSE, sep = ",", header = TRUE) %>%
    pivot_longer(cols = 3:31, names_to = "Year", values_to = "Values") %>%
    pivot_wider(names_from = "Sector", values_from = "Values") %>%
    add_column("Background_use" = NA)
  US_elec_use$Background_use <- US_elec_use$`Total Electricity Use`-US_elec_use$Transportation
  US_elec_use$units <- "kWh"
  US_elec_use[,3:10] <- US_elec_use[,3:10]*1e9
  US_elec_use <- select(US_elec_use, c("Year", "units", "Background_use"))
  US_elec_use$Year <- as.numeric(US_elec_use$Year)
  
  reg_matrix_mix <- do.call(cambium_el_grid_scenario_f, list(output = "electricity", elec_mix_mdl = elec_mix_mdl))[["grid_mix_reg"]] %>%
    filter(Year >= first_proj_yr)
  grid_mix_national <- do.call(cambium_el_grid_scenario_f, list(output = "electricity", elec_mix_mdl = elec_mix_mdl))[["grid_mix_national"]] %>%
    filter(Year >= first_proj_yr)
  reg_yearly_share <- do.call(cambium_el_grid_scenario_f, list(output = "electricity", elec_mix_mdl = elec_mix_mdl))[["reg_yearly_share"]] %>%
    filter(Year >= first_proj_yr)
  
  ## DC is missing in some NREL scenarios
  if (!"DC"%in%reg_matrix_mix$State.Abbr & colnames(reg_matrix_mix)[2] == "State.Abbr") {
    dc_elec_mix <- reg_matrix_mix[which(reg_matrix_mix$State.Abbr == "VA"),]
    dc_elec_mix$State.Abbr <- "DC"
    dc_elec_mix$Fraction[which(dc_elec_mix$Source == "Coal")] <- 0
    dc_elec_mix$Fraction[which(dc_elec_mix$Source == "Oil")] <- 0
    dc_elec_mix$Fraction[which(dc_elec_mix$Source == "Nuclear")] <- 0
    dc_elec_mix$Fraction[which(dc_elec_mix$Source == "Renewable")] <- 1-dc_elec_mix$Fraction[which(dc_elec_mix$Source == "Natural Gas")]
    reg_matrix_mix <- rbind(reg_matrix_mix, dc_elec_mix)
  }
  if (!"DC"%in%reg_yearly_share$State.Abbr & colnames(reg_yearly_share)[2] == "State.Abbr") {
    dc_share <- reg_yearly_share[which(reg_yearly_share$State.Abbr == "CA"),]
    dc_share$State.Abbr <- "DC"
    dc_share$Share <- 4.22852E-05
    reg_yearly_share <- rbind(reg_yearly_share, dc_share)
  }
  
  US_elec_use <- left_join(reg_yearly_share, US_elec_use, by = "Year")
  US_elec_use$Background_use <- US_elec_use$Background_use*US_elec_use$Share
  US_elec_use <- left_join(US_elec_use, reg_matrix_mix, by = c("Year", colnames(reg_matrix_mix)[2]), relationship = "many-to-many")
  US_elec_use$Background_use <- US_elec_use$Background_use*US_elec_use$Fraction
  US_elec_use <- filter(US_elec_use, !is.na(US_elec_use$Background_use)) %>%
    select(-c("Share", "units", "Fraction"))
  US_elec_use$Year <- as.numeric(US_elec_use$Year)
  
  ## Calculate the fraction of natural gas electricity produced for the background and the vehicles - calculated at the national level
  ng_frac_usage <- US_elec_use[which(US_elec_use$Source == "Natural Gas"),] %>%
    select(-c("Source"))
  temp <- left_join(fleet_elec_use_tot_county, select(GIS_matching_matrix, c("FIPS", colnames(reg_matrix_mix)[2])), by = "FIPS", relationship = "many-to-many") %>%
    select(c(colnames(reg_matrix_mix)[2], "Year", "Value")) %>%
    filter(Year >= first_proj_yr)
  temp$Year <- as.numeric(temp$Year)
  temp <- left_join(temp, select(reg_matrix_mix[which(reg_matrix_mix$Source == "Natural Gas"),], -c("Source")), by = c("Year", colnames(reg_matrix_mix)[2]), relationship = "many-to-many")
  temp$Value <- temp$Value*temp$Fraction
  ng_frac_usage <- left_join(ng_frac_usage, select(temp, -c("Fraction")), by = c("Year", colnames(reg_matrix_mix)[2]), relationship = "many-to-many")
  ng_frac_usage <- aggregate(Value ~ ., data = ng_frac_usage, FUN = sum) %>%
    add_column("Total_use" = NA)
  ng_frac_usage$Total_use <- ng_frac_usage$Background_use + ng_frac_usage$Value
  colnames(ng_frac_usage) <- c("Year", colnames(reg_matrix_mix)[2], "Background_frac", "Vehicles_frac", "Total_Use")
  ng_frac_usage <- aggregate(.~Year, data = select(ng_frac_usage, -c(colnames(reg_matrix_mix)[2])), FUN = sum)
  ng_frac_usage$Background_frac <- ng_frac_usage$Background_frac/ng_frac_usage$Total_Use
  ng_frac_usage$Vehicles_frac <- 1-ng_frac_usage$Background_frac
  ng_frac_usage <- add_column(ng_frac_usage, "Rel_ng_demand_elec" = 0)
  for (i in first_proj_yr:last_yr) {
    if (i == first_proj_yr) {
      ng_frac_usage$Rel_ng_demand_elec[i-first_proj_yr+1] <- 1
    } else {
      ng_frac_usage$Rel_ng_demand_elec[i-first_proj_yr+1] <- ng_frac_usage$Total_Use[i-first_proj_yr+1]/ng_frac_usage$Total_Use[i-first_proj_yr]
    }
  }
  ng_frac_usage <- select(ng_frac_usage, -c("Total_Use")) %>%
    add_column("Rel_ng_demand_total" = NA)
  ng_frac_usage$Rel_ng_demand_total <- ng_frac_usage$Rel_ng_demand_elec*share_ng_cons_elec+(1-share_ng_cons_elec)

  ## Load the power plants dataset and calculate the total generation by county
  power_plants <- get_input_f(input_name = 'EIA_Power_Plants') %>%
    filter(State != "Alaska" & State != "Hawaii" & State != "Puerto Rico")
  sources <- c("Coal", "Natural Gas", "Nuclear", "Oil", "Renewable", "Biomass")
  colnames(power_plants)[which(colnames(power_plants) == "County")] <- "CY_NAME"
  colnames(power_plants)[which(colnames(power_plants) == "State")] <- "ST_NAME"
  power_plants <- pivot_longer(power_plants, cols = 19:30, names_to = "Fuel_type", values_to = "Capacity") %>%
    filter(!is.na(Capacity))
  power_plants$Fuel_type[which(power_plants$Fuel_type == "Coal_MW")] <- "Coal"
  power_plants$Fuel_type[which(power_plants$Fuel_type == "NG_MW")] <- "Natural Gas"
  power_plants$Fuel_type[which(power_plants$Fuel_type == "Crude_MW")] <- "Oil"
  power_plants$Fuel_type[which(power_plants$Fuel_type == "Nuclear_MW")] <- "Nuclear"
  power_plants$Fuel_type[grep("_MW",power_plants$Fuel_type)] <- "Renewable"
  power_plants <- aggregate(power_plants$Capacity, list(power_plants$CY_NAME, power_plants$ST_NAME, power_plants$Fuel_type), sum)
  colnames(power_plants) <- c("CY_NAME", "ST_NAME", "Fuel_type", "Capacity_MW")
  power_plants <- left_join(power_plants, select(GIS_matching_matrix, c("CY_NAME", "ST_NAME", "FIPS", colnames(reg_matrix_mix)[2])), by = c("CY_NAME", "ST_NAME")) %>%
    filter(!is.na(FIPS))
  
  # Normalize the electricity production at the GEA and national level
  reg_capacity <- aggregate(Capacity_MW~., data = select(power_plants, -c("CY_NAME", "ST_NAME", "FIPS")), FUN = sum)
  colnames(reg_capacity)[3] <- "Capacity_reg"
  #total_GEA_capacity <- aggregate(Capacity_GEA~Fuel_type, data = GEA_capacity, FUN = sum)
  #colnames(total_GEA_capacity)[2] <- "Capacity_National"
  power_plants <- left_join(power_plants, reg_capacity, by = c(colnames(reg_matrix_mix)[2], "Fuel_type"))
  power_plants$Normalized_Capacity_reg <- power_plants$Capacity_MW/power_plants$Capacity_reg
  #power_plants <- left_join(power_plants, total_GEA_capacity, by = c("Fuel_type"))
  #power_plants$Normalized_Capacity_US <- power_plants$Capacity_MW/power_plants$Capacity_National
  
  
  # Combine with the electricity mix scenario
  colnames(reg_matrix_mix) <- c("Year", colnames(reg_matrix_mix)[2], "Fuel_type", "Value")
  reg_matrix_mix <- aggregate(reg_matrix_mix$Value, list(reg_matrix_mix$Year, reg_matrix_mix[,2], reg_matrix_mix$Fuel_type), sum)
  colnames(reg_matrix_mix) <- c("Year", colnames(power_plants)[6], "Fuel_type", "Value")
  electric_mix <- pivot_wider(reg_matrix_mix[which(reg_matrix_mix$Year >= first_proj_yr),], names_from = Year, values_from = Value)
  power_plants <- left_join(power_plants, electric_mix, by = c(colnames(reg_matrix_mix)[2], "Fuel_type")) %>%
    select(-c("CY_NAME", "ST_NAME", "Capacity_MW", "Capacity_reg"))
  
  # Calculation of the emissions from electricity production for electric vehicles at the county level
  fleet_elec_emissions <- power_plants
  fleet_elec_emissions[,5:33] <- fleet_elec_emissions[,5:33]*fleet_elec_emissions$Normalized_Capacity_reg
  colnames(fleet_elec_emissions)[which(colnames(fleet_elec_emissions) == colnames(reg_matrix_mix)[2])] <- "Reg_entity"
  fleet_elec_use_tot_county <- pivot_wider(filter(fleet_elec_use_tot_county, fleet_elec_use_tot_county$Year >= first_proj_yr), names_from = Year, values_from = Value)
  fleet_elec_use_tot_county <- left_join(fleet_elec_use_tot_county, select(GIS_matching_matrix, c("FIPS", colnames(reg_matrix_mix)[2])), by = c("FIPS"))
  colnames(fleet_elec_use_tot_county)[which(colnames(fleet_elec_use_tot_county) == colnames(reg_matrix_mix)[2])] <- "Reg_entity"
  elec_use_reg <- aggregate(.~ Reg_entity, data = select(fleet_elec_use_tot_county, -c("FIPS", "ST_FIPS", "Fuel", "Unit")), FUN = sum)
  elec_consumption <- left_join(select(fleet_elec_emissions, c("Fuel_type", "Reg_entity")), elec_use_reg, by = c("Reg_entity"))
  fleet_elec_emissions[,5:33] <- fleet_elec_emissions[,5:33]*elec_consumption[,3:31]
  fleet_elec_emissions <- select(fleet_elec_emissions, -c("Normalized_Capacity_reg"))
  
  # Calculation of the background emissions from electricity production at the county level
  US_elec_use$Year <- as.character(US_elec_use$Year)
  colnames(US_elec_use)[4] <- "Fuel_type"
  background_elec_emissions <- select(power_plants, c("Fuel_type", "FIPS", colnames(reg_matrix_mix)[2], "Normalized_Capacity_reg")) %>%
    left_join(US_elec_use, by = c(colnames(reg_matrix_mix)[2], "Fuel_type"), relationship = "many-to-many")
  background_elec_emissions$Background_use <- background_elec_emissions$Background_use*background_elec_emissions$Normalized_Capacity_reg
  background_elec_emissions <- pivot_wider(select(background_elec_emissions, -c("Normalized_Capacity_reg")), values_from = Background_use, names_from = Year)
  
  ## Calculate changes in natural gas demand per PADD
  ng_demand_background <- background_elec_emissions[which(background_elec_emissions$Fuel_type == "Natural Gas"),] %>%
    left_join(select(GIS_matching_matrix, c("FIPS", "PADD")), by = "FIPS") %>%
    pivot_longer(cols = 4:32, names_to = "Year", values_to = "Values")
  ng_demand_background <- aggregate(.~Year+PADD, data = select(ng_demand_background, c("PADD", "Year", "Values")), FUN = sum)
  ng_demand_fleet <- fleet_elec_emissions[which(fleet_elec_emissions$Fuel_type == "Natural Gas"),] %>%
    left_join(select(GIS_matching_matrix, c("FIPS", "PADD")), by = "FIPS") %>%
    pivot_longer(cols = 4:32, names_to = "Year", values_to = "Values")
  ng_demand_fleet <- aggregate(.~Year+PADD, data = select(ng_demand_fleet, c("PADD", "Year", "Values")), FUN = sum)
  for (i in unique(ng_demand_background$PADD)) {
    ng_demand_background$Values[which(ng_demand_background$PADD == i)] <- ng_demand_background$Values[which(ng_demand_background$PADD == i)]/ng_demand_background$Values[which(ng_demand_background$PADD == i & ng_demand_background$Year == min(ng_demand_background$Year))]
    if (unique(ng_demand_fleet$Values)[1]!= 0) {
      ng_demand_fleet$Values[which(ng_demand_fleet$PADD == i)] <- ng_demand_fleet$Values[which(ng_demand_fleet$PADD == i)]/ng_demand_fleet$Values[which(ng_demand_fleet$PADD == i & ng_demand_fleet$Year == min(ng_demand_fleet$Year))]
    }
  }

  ## Combine with the emission factors
  if (electricity_EF_source == "eGrid") {
    ef_data <- get_input_f(input_name = 'ef_pollutants_egrid') %>%
      add_column("Year" = NA) %>%
      select("Year", everything())
  } else if (electricity_EF_source == "AVERT_average") {
    pollutants <- c("NOx", "SO2", "PM25", "NH3", "VOC")
    ef_avert <- filter(get_input_f(input_name = 'AVERT_us_emissions_factors'), Type == "Average")
    ef_avert <- pivot_longer(ef_avert, cols = 5:11, names_to = "Pollutant", values_to = "Emission_rate") %>%
      add_column("Unit" = "lb/MWh") %>%
      filter(Pollutant%in%pollutants) %>%
      select(-c("Type", "Region"))
    ef_egrid <- get_input_f(input_name = 'ef_pollutants_egrid')
    ef_data <- expand.grid(unique(ef_egrid$Fuel), unique(ef_egrid$Pollutant)) %>%
      add_column("Year" = NA)
    ef_data$Var1 <- as.character(ef_data$Var1)
    ef_data$Var2 <- as.character(ef_data$Var2)
    colnames(ef_data) <- c("Fuel", "Pollutant", "Year")
    ef_data <- left_join(select(ef_avert, -c("Year")), ef_data, by = "Pollutant", relationship = "many-to-many") %>%
      relocate(Year, .before = Name)
    colnames(ef_data)[2] <- "AVERT_region"
    ef_data <- relocate(ef_data, Fuel, .before = Pollutant)
  }
  years <- first_proj_yr:last_yr
  fun <- function(i) {
    ef_data$Year <- i
    if (i > first_proj_yr) {
      ef_data$Emission_rate <- NA
    }
    return(ef_data)
  }
  ef_data <- do.call(rbind, lapply(years, fun))
  ### Add the option to converge emission factors over the years
  if (dynamic_efs == "y") {
    lowest_efs <- aggregate(Emission_rate~Fuel+Pollutant, data = select(ef_data, c("Fuel", "Pollutant", "Emission_rate")), FUN = min)
    colnames(lowest_efs)[3] <- "Lowest_EF"
    ef_data <- left_join(ef_data, lowest_efs, by = c("Fuel", "Pollutant"))
    ef_data$Emission_rate[which(ef_data$Year == efs_convergence+first_proj_yr)] <- ef_data$Lowest_EF[which(ef_data$Year == efs_convergence+first_proj_yr)]
    if (efs_convergence+first_proj_yr < last_yr) {
      ef_data$Emission_rate[which(ef_data$Year <= last_yr & ef_data$Year > efs_convergence+first_proj_yr)] <- ef_data$Lowest_EF[which(ef_data$Year == efs_convergence+first_proj_yr)]
    }
    ef_data <- select(ef_data, -c("Lowest_EF"))
    fuels <- unique(ef_data$Fuel)
    pollutants <- unique(ef_data$Pollutant)
    temp <- expand.grid(fuels, pollutants)
    fun <- function(i) {
      index <- which(ef_data$Fuel == temp[i,1] & ef_data$Pollutant == temp[i,2])
      ef_data$Emission_rate[index] <- na.approx(ef_data$Emission_rate[index])
      return(ef_data[index,])
    }
    ef_data <- do.call(rbind, lapply(1:dim(temp)[1], fun))
  } else if (efs_yearly_change == "y") {
    ef_data$Emission_rate[which(ef_data$Year > first_proj_yr)] <- ef_data$Emission_rate[which(ef_data$Year == first_proj_yr)]
    yearly_efs_change_rate <- read.csv(paste0(getwd(), "/inputs/air_quality/EFs_Annual_Change.csv"))
    ef_data <- left_join(ef_data, yearly_efs_change_rate, by = c("Pollutant", "Fuel"))
    ef_data$Emission_rate <- ef_data$Emission_rate*(1+ef_data$CAGR/100)^(ef_data$Year-min(ef_data$Year))
    ef_data <- select(ef_data, -c("CAGR"))
  } else {
    ef_data$Emission_rate[which(ef_data$Year > first_proj_yr)] <- ef_data$Emission_rate[which(ef_data$Year == first_proj_yr)]
  }
  if (electricity_EF_source == "AVERT_average") {
    ef_data <- ef_data %>%
      left_join(select(GIS_matching_matrix, c("AVERT_region", colnames(reg_matrix_mix)[2], "FIPS")), by = "AVERT_region", relationship = "many-to-many") %>%
      filter(!is.na(FIPS))
  } else if (electricity_EF_source == "eGrid") {
    ef_data <- ef_data %>%
      left_join(select(GIS_matching_matrix, c("eGRID_subregion", colnames(reg_matrix_mix)[2], "FIPS")), by = "eGRID_subregion", relationship = "many-to-many") %>%
      filter(!is.na(FIPS))
  }
  colnames(ef_data) <- c("Year", "reg_entity", "Fuel_type", "Pollutant", "Emission_factor", "Unit", colnames(reg_matrix_mix)[2], "FIPS")
  ef_data$Fuel_type[which(ef_data$Fuel_type == "Renewables")] <- "Renewable"
  ef_data$Emission_factor <- ef_data$Emission_factor*0.454*1e-6
  ef_data$Unit <- "tons/kWh"
  ef_data <- pivot_wider(ef_data, names_from = Pollutant, values_from = Emission_factor)
  ef_data$Year <- as.character(ef_data$Year)
  background_elec_emissions <- pivot_longer(background_elec_emissions, cols = 4:32, names_to = "Year", values_to = "Production")
  background_elec_emissions <- left_join(background_elec_emissions, select(ef_data, -c("reg_entity", colnames(reg_matrix_mix)[2])), by = c("FIPS", "Fuel_type", "Year"))
  background_elec_emissions[,7:11] <- background_elec_emissions[,7:11]*background_elec_emissions$Production
  background_elec_emissions$Unit <- "tons"
  fleet_elec_emissions <- pivot_longer(fleet_elec_emissions, cols = 4:32, names_to = "Year", values_to = "Production")
  fleet_elec_emissions <- left_join(fleet_elec_emissions, select(ef_data, -c("reg_entity", colnames(reg_matrix_mix)[2])), by = c("FIPS", "Fuel_type", "Year"))
  fleet_elec_emissions[,7:11] <- fleet_elec_emissions[,7:11]*fleet_elec_emissions$Production
  fleet_elec_emissions$Unit <- "tons"
  
  ## Generate the final dataset
  background_elec_emissions <- select(background_elec_emissions, -c("Production")) %>%
    filter(Fuel_type != "renewables")
  colnames(background_elec_emissions)[which(colnames(background_elec_emissions) == colnames(reg_matrix_mix)[2])] <- "Reg_entity"
  fleet_elec_emissions <- select(fleet_elec_emissions, -c("Production")) %>%
    filter(Fuel_type != "renewables")
  
  ## Generate county and national files
  electricity_emissions_fleet_county <- aggregate(.~Year+FIPS, data = select(fleet_elec_emissions, -c("Fuel_type", "Reg_entity", "Unit")), FUN = sum)
  electricity_emissions_fleet_state <- aggregate(.~Year+ST_FIPS, data = select(left_join(electricity_emissions_fleet_county, select(GIS_matching_matrix, c("FIPS", "ST_FIPS")), by = "FIPS"), -c("FIPS")), FUN = sum) 
  electricity_emissions_fleet <- aggregate(.~Year, data = select(electricity_emissions_fleet_state, -c("ST_FIPS")), FUN = sum)
  electricity_emissions_background_county <- aggregate(.~Year+FIPS, data = select(background_elec_emissions, -c("Fuel_type", "Reg_entity", "Unit")), FUN = sum)
  electricity_emissions_background_state <- aggregate(.~Year+ST_FIPS, data = select(left_join(electricity_emissions_background_county, select(GIS_matching_matrix, c("FIPS", "ST_FIPS")), by = "FIPS"), -c("FIPS")), FUN = sum) 
  electricity_emissions_background <- aggregate(.~Year, data = select(electricity_emissions_background_state, -c("ST_FIPS")), FUN = sum)
  
  ## Modify the ng demand files in the no elec scenario
  if (grepl("no_elec", scenario_id)) {
    ng_demand_background$Values <- 0
    ng_demand_fleet$Values <- 0
    ng_frac_usage$Vehicles_frac <- 0
    ng_frac_usage$Rel_ng_demand_elec <- 1
    ng_frac_usage$Rel_ng_demand_total <- 1
  }
  
  ## Export the final datasets
  write.csv(electricity_emissions_fleet_county, paste0(results_path, "/electricity_emissions_fleet_county.csv"))
  write.csv(electricity_emissions_fleet_state, paste0(results_path, "/electricity_emissions_fleet_state.csv"))
  write.csv(electricity_emissions_fleet, paste0(results_path, "/electricity_emissions_fleet.csv"))
  write.csv(electricity_emissions_background_county, paste0(results_path, "/electricity_emissions_background_county.csv"))
  write.csv(electricity_emissions_background_state, paste0(results_path, "/electricity_emissions_background_state.csv"))
  write.csv(electricity_emissions_background, paste0(results_path, "/electricity_emissions_background.csv"))
  write.csv(fleet_elec_emissions, paste0(results_path, "/electricity_emissions_fleet_detailed.csv"))
  write.csv(background_elec_emissions, paste0(results_path, "/electricity_emissions_background_detailed.csv"))
  write.csv(ng_demand_background, paste0(results_path, "/ng_demand_background.csv"))
  write.csv(ng_demand_fleet, paste0(results_path, "/ng_demand_fleet.csv"))
  write.csv(ng_frac_usage, paste0(results_path, "/ng_frac_usage.csv"))
  
  return(list(fleet_elec_emissions = fleet_elec_emissions,
              background_elec_emissions = background_elec_emissions,
              ng_demand_background = ng_demand_background,
              ng_demand_fleet = ng_demand_fleet,
              ng_frac_usage = ng_frac_usage))
}
