electric_grid_emissions_f <- function(fleet_composition, fleet_elec_use_tot_state, fleet_elec_use_tot_county, fleet_electricity_consumption_source = NA, scenario_id = NA, electricity_EF_source = NA, last_yr = NA, electricity_EF_change_scenario = NA, fleet_id = NA, elec_ef_source = NA, emissions_multiplier_SO2 = NA, emissions_multiplier_NOx = NA, emissions_multiplier_PM25 = NA) {
  # Computes the regional emissions of pollutants generated by the electricity necessary to power battery electric vehicles. 
  attribute_f("electric_grid_emissions_f")
  results_path <- paste0(getwd(), "/outputs/air_quality/", Sys.Date(), "_", scenario_id, "_results")
  first_proj_yr <- 2022
  GIS_matching_matrix <- read.csv(paste0(getwd(), "/inputs/air_quality/GIS_matching_matrix.csv"))
  # Calculation of the emissions factors by state using one of the four potential EFs sources: eGRID, AVERT, or GREET/CAMBIUM with the corresponding regions
  # Integrate emissions factors and regions from different sources: AVERT/AVERT regions; eGRID/eGRID regions and NERC; CAMBIUM/GEA regions
  if (electricity_EF_source == "AVERT") {
    if (electricity_EF_change_scenario == "AEO22") {
      yearly_EF_change <- get_input_f(input_name = 'AEO2022_Electricity_EF_Yearly_Change')
    }
    AVERT_emissions <- get_input_f(input_name = 'AVERT_us_emissions_factors') %>%
      add_column("Power_demand" = 0)
    AVERT_regions <- unique(AVERT_emissions$Name)
    years <- first_proj_yr:last_yr
    AVERT_emissions_temp <- AVERT_emissions
    # Calculation of the total emissions in each grouping region
    for (i in years) {
      AVERT_emissions_temp$Year <- i
      if (electricity_EF_change_scenario == "AEO22") {
        electricity_EF_change <- yearly_EF_change$`Yearly change`[which(yearly_EF_change$Year == i)]/100
      }
      for (j in AVERT_regions) {
        counties <- GIS_matching_matrix$FIPS[which(GIS_matching_matrix$AVERT_Region == j)]
        regional_elec_demand <- sum(fleet_elec_use_tot_county$Value[which(fleet_elec_use_tot_county$FIPS%in%counties & fleet_elec_use_tot_county$Year == i)])
        AVERT_emissions_temp$Power_demand[which(AVERT_emissions_temp$Name == j)] <- regional_elec_demand
      }
      AVERT_emissions_temp[,4:10] <- AVERT_emissions_temp[,4:10]*(1+electricity_EF_change)
      if (i == first_proj_yr) {
        AVERT_emissions <- AVERT_emissions_temp
      } else {
        AVERT_emissions <- rbind(AVERT_emissions, AVERT_emissions_temp)
      }
    }
    emissions_matrix <- select(AVERT_emissions, -c("O3_EF", "CO2_EF"))
  } else if (electricity_EF_source == "CAMBIUM") {
    electricity_mix <- do.call(cambium_el_grid_scenario_f, list(output = "electricity"))[["reg_matrix_mix"]]
    #if (fleet_id == "2020_fleet") {
    #  electricity_mix <- filter(electricity_mix, electricity_mix$Year <= 2020)
    #  electricity_mix_temp <- filter(electricity_mix, electricity_mix$Year == 2020)
    #  years <- (2020+1):last_yr
    #  for (i in years) {
    #    electricity_mix_temp$Year <- i
    #    electricity_mix <- rbind(electricity_mix, electricity_mix_temp)
    #  }
    #}
    #CAMBIUM_emissions <- data.frame(unique(electricity_mix$Region)) %>%
    CAMBIUM_emissions <- data.frame(unique(GIS_matching_matrix$ReEDS_BA)) %>%
      add_column("Year" = NA) %>%
      add_column("Name" = NA) %>%
      add_column("SO2_EF" = 0) %>%
      add_column("NOx_EF" = 0) %>%
      add_column("PM25_EF" = 0) %>%
      add_column("VOC_EF" = 0) %>%
      add_column("NH3_EF" = 0) %>%
      add_column("Power_demand" = NA)
    colnames(CAMBIUM_emissions)[1] <- "Region"
    CAMBIUM_emissions$Name <- CAMBIUM_emissions$Region
    CAMBIUM_emissions <-  relocate(CAMBIUM_emissions, "Year", .before = Region)
    years <- first_proj_yr:max(electricity_mix$Year)
    regions <- unique(CAMBIUM_emissions$Region)
    electricity_sources <- unique(electricity_mix$Source)
    elec_techno_match <- get_input_f(input_name = "model_matching_electricity")
    if (elec_ef_source == "greet") {
      EF_elec_GREET  <- get_input_f(input_name = 'EF_elec_GREET') 
      for (i in years) {
        emissions_matrix_temp <- CAMBIUM_emissions
        emissions_matrix_temp$Year <- i
        #EF_matrix <- matrix(0, nrow = length(regions), ncol = length(electricity_sources))
        for (j in regions) {
          # Addition of the power demand data
          counties <- GIS_matching_matrix$FIPS[which(GIS_matching_matrix$ReEDS_BA == j)]
          #counties <- GIS_matching_matrix$FIPS[which(GIS_matching_matrix$CAMBIUM_GEA == j)]
          regional_elec_demand <- sum(fleet_elec_use_tot_county$Value[which(fleet_elec_use_tot_county$FIPS%in%counties & fleet_elec_use_tot_county$Year == i)])
          emissions_matrix_temp$Power_demand[which(emissions_matrix_temp$Year == i & emissions_matrix_temp$Region == j)] <- regional_elec_demand
          # Calculation of the emissions factors
          for (k in electricity_sources) {
            fraction <- electricity_mix$Value[which(electricity_mix$Year == i & electricity_mix$Region == j & electricity_mix$Source == k)]
            row <- which(EF_elec_GREET$Technology == elec_techno_match$GREET[which(elec_techno_match$Own == k)] & EF_elec_GREET$`Emission type` == "Direct Combustion")
            if (length(row) == 0) {
              source_EF_SO2 <- 0
              source_EF_NOx <- 0
              source_EF_PM25 <- 0
              source_EF_VOC <- 0
              source_EF_NH3 <- 0
            } else {
              source_EF_SO2 <- EF_elec_GREET$SOx[row]
              source_EF_NOx <-EF_elec_GREET$NOx[row]
              source_EF_PM25 <- EF_elec_GREET$PM2.5[row]
              source_EF_VOC <- EF_elec_GREET$VOC[row]
              source_EF_NH3 <- 0
            }
            temp <- which(emissions_matrix_temp$Year == i & emissions_matrix_temp$Region == j)
            emissions_matrix_temp$SO2_EF[temp] <- emissions_matrix_temp$SO2_EF[temp]+fraction*source_EF_SO2
            emissions_matrix_temp$NOx_EF[temp] <- emissions_matrix_temp$NOx_EF[temp]+fraction*source_EF_NOx
            emissions_matrix_temp$PM25_EF[temp] <- emissions_matrix_temp$PM25_EF[temp]+fraction*source_EF_PM25
            emissions_matrix_temp$VOC_EF[temp] <- emissions_matrix_temp$VOC_EF[temp]+fraction*source_EF_VOC
            emissions_matrix_temp$NH3_EF[temp] <- emissions_matrix_temp$NH3_EF[temp]+fraction*source_EF_NH3
          }
        }
        if (i == years[1]) {
          output <- emissions_matrix_temp
        } else {
          output <- rbind(output, emissions_matrix_temp)
        }
      }
    } else if (elec_ef_source == "egrid") {
      EF_elec_egrid  <- get_input_f(input_name = 'ef_pollutants_egrid') 
      EF_elec_egrid$Emission_rate <- EF_elec_egrid$Emission_rate/1000*453.59237
      EF_elec_egrid$Unit <- "g/kWh"
      for (i in years) {
        emissions_matrix_temp <- CAMBIUM_emissions
        emissions_matrix_temp$Year <- i
        #EF_matrix <- matrix(0, nrow = length(regions), ncol = length(electricity_sources))
        for (j in regions) {
          # Addition of the power demand data
          #counties <- GIS_matching_matrix$FIPS[which(GIS_matching_matrix$CAMBIUM_GEA == j)]
          counties <- GIS_matching_matrix$FIPS[which(GIS_matching_matrix$ReEDS_BA == j)]
          regional_elec_demand <- sum(fleet_elec_use_tot_county$Value[which(fleet_elec_use_tot_county$FIPS%in%counties & fleet_elec_use_tot_county$Year == i)])
          emissions_matrix_temp$Power_demand[which(emissions_matrix_temp$Year == i & emissions_matrix_temp$Region == j)] <- regional_elec_demand
          egrid_region <- GIS_matching_matrix$CAMBIUM_GEA[which(GIS_matching_matrix$ReEDS_BA == j)]
          egrid_region <- str_split(egrid_region, "c")[[1]][1]
          #egrid_region <- str_split(j, "c")[[1]][1]
          # Calculation of the emissions factors
          for (k in electricity_sources) {
            fuel <- elec_techno_match$eGRID[which(elec_techno_match$Own == k)]
            ######
            elec_mix_region <- unique(GIS_matching_matrix$CAMBIUM_GEA[which(GIS_matching_matrix$ReEDS_BA == j)])
            ####
            #fraction <- electricity_mix$Value[which(electricity_mix$Year == i & electricity_mix$Region == j & electricity_mix$Source == k)]
            fraction <- electricity_mix$Value[which(electricity_mix$Year == i & electricity_mix$Region == elec_mix_region & electricity_mix$Source == k)]
            source_EF_SO2 <- EF_elec_egrid$Emission_rate[which(EF_elec_egrid$eGrid_region == egrid_region & EF_elec_egrid$Fuel == fuel & EF_elec_egrid$Pollutant == "SO2")]
            source_EF_NOx <- EF_elec_egrid$Emission_rate[which(EF_elec_egrid$eGrid_region == egrid_region & EF_elec_egrid$Fuel == fuel & EF_elec_egrid$Pollutant == "NOx")]
            source_EF_PM25 <- EF_elec_egrid$Emission_rate[which(EF_elec_egrid$eGrid_region == egrid_region & EF_elec_egrid$Fuel == fuel & EF_elec_egrid$Pollutant == "PM25")]
            source_EF_VOC <- 0
            source_EF_NH3 <- 0
            if (length(source_EF_SO2) == 0) {
              source_EF_SO2 <- EF_elec_egrid$Emission_rate[which(EF_elec_egrid$eGrid_region == "Average" & EF_elec_egrid$Fuel == fuel & EF_elec_egrid$Pollutant == "SO2")]
            }
            if (length(source_EF_NOx) == 0) {
              source_EF_NOx <- EF_elec_egrid$Emission_rate[which(EF_elec_egrid$eGrid_region == "Average" & EF_elec_egrid$Fuel == fuel & EF_elec_egrid$Pollutant == "NOx")]
            }
            if (length(source_EF_PM25) == 0) {
              source_EF_PM25 <- EF_elec_egrid$Emission_rate[which(EF_elec_egrid$eGrid_region == "Average" & EF_elec_egrid$Fuel == fuel & EF_elec_egrid$Pollutant == "PM25")]
            }
            if (source_EF_SO2 == 0) {
              source_EF_SO2 <- EF_elec_egrid$Emission_rate[which(EF_elec_egrid$eGrid_region == "Average" & EF_elec_egrid$Fuel == fuel & EF_elec_egrid$Pollutant == "SO2")]
            }
            if (source_EF_NOx == 0) {
              source_EF_NOx <- EF_elec_egrid$Emission_rate[which(EF_elec_egrid$eGrid_region == "Average" & EF_elec_egrid$Fuel == fuel & EF_elec_egrid$Pollutant == "NOx")]
            }
            temp <- which(emissions_matrix_temp$Year == i & emissions_matrix_temp$Region == j)
            emissions_matrix_temp$SO2_EF[temp] <- emissions_matrix_temp$SO2_EF[temp]+fraction*source_EF_SO2
            emissions_matrix_temp$NOx_EF[temp] <- emissions_matrix_temp$NOx_EF[temp]+fraction*source_EF_NOx
            emissions_matrix_temp$PM25_EF[temp] <- emissions_matrix_temp$PM25_EF[temp]+fraction*source_EF_PM25
            emissions_matrix_temp$VOC_EF[temp] <- emissions_matrix_temp$VOC_EF[temp]+fraction*source_EF_VOC
            emissions_matrix_temp$NH3_EF[temp] <- emissions_matrix_temp$NH3_EF[temp]+fraction*source_EF_NH3
          }
        }
        if (i == years[1]) {
          output <- emissions_matrix_temp
        } else {
          output <- rbind(output, emissions_matrix_temp)
        }
      }
    }
    CAMBIUM_emissions <- output
    emissions_matrix <- CAMBIUM_emissions
  }
  emissions_matrix <- emissions_matrix %>%
      add_column("SO2_Emissions" = 0) %>%
      add_column("NOx_Emissions" = 0) %>%
      add_column("PM25_Emissions" = 0) %>%
      add_column("VOC_Emissions" = 0) %>%
      add_column("NH3_Emissions" = 0) %>%
      add_column("Unit" = "g")
  emissions_matrix$SO2_Emissions <- emissions_matrix$SO2_EF*emissions_matrix$Power_demand*emissions_multiplier_SO2
  emissions_matrix$NOx_Emissions <- emissions_matrix$NOx_EF*emissions_matrix$Power_demand*emissions_multiplier_NOx
  emissions_matrix$PM25_Emissions <- emissions_matrix$PM25_EF*emissions_matrix$Power_demand*emissions_multiplier_PM25
  emissions_matrix$VOC_Emissions <- emissions_matrix$VOC_EF*emissions_matrix$Power_demand
  emissions_matrix$NH3_Emissions <- emissions_matrix$NH3_EF*emissions_matrix$Power_demand
  emissions_matrix <- select(emissions_matrix, -c("SO2_EF", "NOx_EF", "PM25_EF", "VOC_EF", "NH3_EF"))
    # Calculation of the emissions in each county
  COBRA_baseline <- get_input_f(input_name = 'COBRA_emissions_baseline')
  COBRA_baseline <- filter(COBRA_baseline, COBRA_baseline$TIER1 == 1)
  elec_emissions_by_county <- data.frame(unique(GIS_matching_matrix$FIPS)) %>%
    add_column("State" = NA) %>%
    add_column("Fuel" = "Electricity") %>%
    add_column("Year" = NA) %>%
    add_column("Unit" = "tons") %>%
    add_column("SO2" = 0) %>%
    add_column("NOx" = 0) %>%
    add_column("PM25" = 0) %>%
    add_column("VOC" = 0) %>%
    add_column("NH3" = 0)
  colnames(elec_emissions_by_county)[1] <- c("FIPS")
  for (i in years) {
    for (j in 1:length(elec_emissions_by_county$FIPS)) {
      sourceindx <- GIS_matching_matrix$COBRA_SOURCEINDX[which(GIS_matching_matrix$FIPS == elec_emissions_by_county$FIPS[j])]
      if (electricity_EF_source == "AVERT") {
        region <- GIS_matching_matrix$AVERT_Region[which(GIS_matching_matrix$FIPS == elec_emissions_by_county$FIPS[j])]
        counties <- GIS_matching_matrix$COBRA_SOURCEINDX[which(GIS_matching_matrix$AVERT_Region == region)]
      } else if (electricity_EF_source == "CAMBIUM") {
        #region <- GIS_matching_matrix$CAMBIUM_GEA[which(GIS_matching_matrix$FIPS == elec_emissions_by_county$FIPS[j])]
        region <- GIS_matching_matrix$ReEDS_BA[which(GIS_matching_matrix$FIPS == elec_emissions_by_county$FIPS[j])]
        #counties <- GIS_matching_matrix$COBRA_SOURCEINDX[which(GIS_matching_matrix$CAMBIUM_GEA == region)]
        counties <- GIS_matching_matrix$COBRA_SOURCEINDX[which(GIS_matching_matrix$ReEDS_BA == region)]
      }
      state <- GIS_matching_matrix$ST_FIPS[which(GIS_matching_matrix$FIPS == elec_emissions_by_county$FIPS[j])]
      emissions <- which(emissions_matrix$Year == i & emissions_matrix$Name == region)
      elec_emissions_by_county$SO2[j] <- sum(COBRA_baseline$SO2[which(COBRA_baseline$sourceindx == sourceindx)])/sum(COBRA_baseline$SO2[which(COBRA_baseline$sourceindx%in%counties)])*emissions_matrix$SO2_Emissions[emissions]/1e6
      elec_emissions_by_county$NOx[j] <- sum(COBRA_baseline$NO2[which(COBRA_baseline$sourceindx == sourceindx)])/sum(COBRA_baseline$NO2[which(COBRA_baseline$sourceindx%in%counties)])*emissions_matrix$NOx_Emissions[emissions]/1e6
      elec_emissions_by_county$PM25[j] <- sum(COBRA_baseline$PM25[which(COBRA_baseline$sourceindx == sourceindx)])/sum(COBRA_baseline$PM25[which(COBRA_baseline$sourceindx%in%counties)])*emissions_matrix$PM25_Emissions[emissions]/1e6
      elec_emissions_by_county$VOC[j] <- sum(COBRA_baseline$VOC[which(COBRA_baseline$sourceindx == sourceindx)])/sum(COBRA_baseline$VOC[which(COBRA_baseline$sourceindx%in%counties)])*emissions_matrix$VOC_Emissions[emissions]/1e6
      elec_emissions_by_county$NH3[j] <- sum(COBRA_baseline$NH3[which(COBRA_baseline$sourceindx == sourceindx)])/sum(COBRA_baseline$NH3[which(COBRA_baseline$sourceindx%in%counties)])*emissions_matrix$NH3_Emissions[emissions]/1e6
      elec_emissions_by_county$Year[j] <- i
      elec_emissions_by_county$State[j] <- state
    }
    if (i == first_proj_yr) {
       temp <- elec_emissions_by_county
    } else {
      temp <- rbind(temp, elec_emissions_by_county)
    }
  }
  elec_emissions_by_county <- temp
  elec_emissions_by_county$SO2[which(elec_emissions_by_county$SO2 == "NaN")] <- 0
  elec_emissions_by_county$NOx[which(elec_emissions_by_county$NOx == "NaN")] <- 0
  elec_emissions_by_county$PM25[which(elec_emissions_by_county$PM25 == "NaN")] <- 0
  elec_emissions_by_county$VOC[which(elec_emissions_by_county$VOC == "NaN")] <- 0
  elec_emissions_by_county$NH3[which(elec_emissions_by_county$NH3 == "NaN")] <- 0
  # Generation of the final files, aggregation and export in .csv
  fleet_emissions_elec_county <- elec_emissions_by_county
  fleet_emissions_elec_state <- aggregate(. ~ State + Fuel + Year + Unit, data = select(fleet_emissions_elec_county, -c("FIPS")), FUN = sum)
  fleet_emissions_elec_total <- aggregate(. ~ Fuel + Year + Unit, data = select(fleet_emissions_elec_state, -c("State")), FUN = sum)
  write.csv(fleet_emissions_elec_county, paste0(results_path, "/emissions_elec_fleet_county.csv"))
  write.csv(fleet_emissions_elec_state, paste0(results_path, "/emissions_elec_fleet_state.csv"))
  write.csv(fleet_emissions_elec_total, paste0(results_path, "/emissions_elec_fleet.csv"))
  # Calculation of the total emissions from electricity
  total_electricity_production <- do.call(cambium_el_grid_scenario_f, list(output = "total_emissions_electricity"))[["total_electricity_production"]] %>%
    add_column("Fleet_consumption" = NA) %>%
    add_column("Non-fleet_consumption" = NA) %>%
    add_column("Total_consumption" = NA)
  years <- unique(total_electricity_production$Year)
  frac_elec_non_transport <- get_input_f(input_name = 'AEO23_frac_elec_non_transport')
  for (i in years) {
    total_electricity_production$Fleet_consumption[which(total_electricity_production$Year == i)] <- sum(fleet_elec_use_tot_state$Value[which(fleet_elec_use_tot_state$Year == i)])
    total_electricity_production$`Non-fleet_consumption`[which(total_electricity_production$Year == i)] <- as.numeric(total_electricity_production$Electricity_production[which(total_electricity_production$Year == i)])*frac_elec_non_transport$Frac_non_transportation[which(frac_elec_non_transport$Year == i)]
  }
  total_electricity_production$Total_consumption <- total_electricity_production$Fleet_consumption+total_electricity_production$`Non-fleet_consumption`
  

  
  
    
    
    
  
  
  
  
  
  parameter <- 1
  if (parameter == 0) {
  if (electricity_scenario == "current_grid") {
    if (fleet_electricity_consumption_source == "FLAME" & electricity_EF_source == "eGRID") {
      eGRID_emissions_factors <- read.csv(paste0(getwd(), "/inputs/air_quality/eGRID_Emissions_Factors.csv"), fileEncoding="UTF-8-BOM")
      COBRA_state_correspondance <- read.csv(paste0(getwd(), "/inputs/air_quality/list_states.csv"), sep = ";")
      state_emission_factors <- eGRID_emissions_factors %>%
        add_column("State_ID" = NA) %>%
        add_column("VOC" = 0) %>%
        add_column("NH3" = 0) %>%
        relocate(State_ID, .after = State)
      state_emission_factors$State <- toupper(state_emission_factors$State)
      for (i in 1:dim(state_emission_factors)[1]) {
        state_emission_factors$State_ID[i] <- COBRA_state_correspondance$stateID[which(COBRA_state_correspondance$stateName == state_emission_factors$State[i])]
      }
      
      
      if (electricity_EF_change_scenario == "AEO22") {
        yearly_EF_change <- get_input_f(input_name = 'AEO2022_Electricity_EF_Yearly_Change')
      }
      for (i in (first_proj_yr):last_yr) {
        temp_state_emission_factors <- filter(state_emission_factors, state_emission_factors$Year == i-1)
        temp_state_emission_factors$Year <- i
        if (electricity_EF_change_scenario == "AEO22") {
          electricity_EF_change <- yearly_EF_change$`Yearly change`[which(yearly_EF_change$Year == i)]/100
        }
        temp_state_emission_factors[,4:8] <- temp_state_emission_factors[,4:8]*(1+electricity_EF_change)
        state_emission_factors <- rbind(state_emission_factors, temp_state_emission_factors)
      }
    } else if (fleet_electricity_consumption_source == "FLAME" & electricity_EF_source == "COBRA") {
      COBRA_state_correspondance <- read.csv(paste0(getwd(), "/inputs/air_quality/list_states.csv"), sep = ";")
      COBRA_emissions_baseline <- get_input_f(input_name = 'COBRA_emissions_baseline')
      COBRA_electricity_emissions <- filter(COBRA_emissions_baseline, COBRA_emissions_baseline$TIER1 == 1)
      eGRID_electricity_generation_by_state <- read.csv(paste0(getwd(), "/inputs/air_quality/Total_generation_by_state_2021.csv"))
      colnames(eGRID_electricity_generation_by_state) <- c("State", "Electricity_kWh")
      eGRID_electricity_generation_by_state$Electricity_kWh <- eGRID_electricity_generation_by_state$Electricity_kWh*1000
      COBRA_el_emissions_by_state <- data.frame(eGRID_electricity_generation_by_state$State) %>%
        add_column("Year" = 2021) %>%
        add_column("State_ID" = NA) %>%
        add_column("Electric_production" = NA) %>%
        add_column("SO2" = NA) %>%
        add_column("NOx" = NA) %>%
        add_column("PM25" = NA) %>%
        add_column("NH3" = NA) %>%
        add_column("VOC" = NA) %>%
        add_column("SOA" = NA)
      colnames(COBRA_el_emissions_by_state)[1] <- c("State")
      COBRA_el_emissions_by_state <- filter(COBRA_el_emissions_by_state, COBRA_el_emissions_by_state$State!="US")
      for (i in 1:dim(COBRA_el_emissions_by_state)[1]) {
        COBRA_el_emissions_by_state$State_ID[i] <- COBRA_state_correspondance$stateID[which(COBRA_state_correspondance$stateName == COBRA_el_emissions_by_state$State[i])]
        COBRA_el_emissions_by_state$Electric_production[i] <- eGRID_electricity_generation_by_state$Electricity_kWh[which(eGRID_electricity_generation_by_state$State == COBRA_el_emissions_by_state$State[i])]
        COBRA_el_emissions_by_state$SO2[i] <- sum(COBRA_electricity_emissions$SO2[which(COBRA_electricity_emissions$stid == COBRA_el_emissions_by_state$State_ID[i])])*1E6/COBRA_el_emissions_by_state$Electric_production[i]
        COBRA_el_emissions_by_state$NOx[i] <- sum(COBRA_electricity_emissions$NO2[which(COBRA_electricity_emissions$stid == COBRA_el_emissions_by_state$State_ID[i])])*1E6/COBRA_el_emissions_by_state$Electric_production[i]
        COBRA_el_emissions_by_state$PM25[i] <- sum(COBRA_electricity_emissions$PM25[which(COBRA_electricity_emissions$stid == COBRA_el_emissions_by_state$State_ID[i])])*1E6/COBRA_el_emissions_by_state$Electric_production[i]
        COBRA_el_emissions_by_state$NH3[i] <- sum(COBRA_electricity_emissions$NH3[which(COBRA_electricity_emissions$stid == COBRA_el_emissions_by_state$State_ID[i])])*1E6/COBRA_el_emissions_by_state$Electric_production[i]
        COBRA_el_emissions_by_state$VOC[i] <- sum(COBRA_electricity_emissions$VOC[which(COBRA_electricity_emissions$stid == COBRA_el_emissions_by_state$State_ID[i])])*1E6/COBRA_el_emissions_by_state$Electric_production[i]
        COBRA_el_emissions_by_state$SOA[i] <- sum(COBRA_electricity_emissions$SOA[which(COBRA_electricity_emissions$stid == COBRA_el_emissions_by_state$State_ID[i])])*1E6/COBRA_el_emissions_by_state$Electric_production[i]
      }
      state_emission_factors <- COBRA_el_emissions_by_state
      if (electricity_EF_change_scenario == "AEO22") {
        yearly_EF_change <- get_input_f(input_name = 'AEO2022_Electricity_EF_Yearly_Change')
      }
      for (i in (first_proj_yr):last_yr) {
        temp_state_emission_factors <- filter(state_emission_factors, state_emission_factors$Year == i-1)
        temp_state_emission_factors$Year <- i
        if (electricity_EF_change_scenario == "AEO22") {
          electricity_EF_change <- yearly_EF_change$`Yearly change`[which(yearly_EF_change$Year == i)]/100
        }
        temp_state_emission_factors[,5:10] <- temp_state_emission_factors[,5:10]*(1+electricity_EF_change)
        state_emission_factors <- rbind(state_emission_factors, temp_state_emission_factors)
      }
      state_emission_factors <- select(state_emission_factors, -c("Electric_production"))
    } else if (fleet_electricity_consumption_source == "FLAME" & electricity_EF_source == "AVERT") {
      AVERT_emissions_factors <- get_input_f(input_name = 'AVERT_us_emissions_factors')
      AVERT_state_allocation_factors <- read.csv(paste0(getwd(), "/inputs/air_quality/AVERT_us_electricity_regions_states_allocation.csv"), fileEncoding="UTF-8-BOM")
      COBRA_state_correspondance <- read.csv(paste0(getwd(), "/inputs/air_quality/list_states.csv"), sep = ";")
      AVERT_emissions_factors$Name <- toupper(AVERT_emissions_factors$Name)
      AVERT_state_allocation_factors$State <- toupper(AVERT_state_allocation_factors$State)
      COBRA_state_correspondance$stateName <- toupper(COBRA_state_correspondance$stateName)
      # Calculation of the emission factors for each state based on the regions EFs and the state allocation factors
      state_emission_factors <- data.frame(unique(COBRA_state_correspondance$stateName)) %>%
        add_column("Year" = first_proj_yr-1) %>%
        add_column("State_ID" = COBRA_state_correspondance$stateID) %>%
        add_column("SO2" = 0) %>%
        add_column("NOx" = 0) %>%
        add_column("O3" = 0) %>%
        add_column("CO2" = 0) %>%
        add_column("PM25" = 0) %>%
        add_column("VOC" = 0) %>%
        add_column("NH3" = 0)
      colnames(state_emission_factors)[1] <- "State"
      # Open the yearly EF change dataset
      if (electricity_EF_change_scenario == "AEO22") {
        yearly_EF_change <- get_input_f(input_name = 'AEO2022_Electricity_EF_Yearly_Change')
      }
      # Update emissions factors considering a decrease in the emission factors of the generated electricity
      for (i in (first_proj_yr):last_yr) {
        if (electricity_EF_change_scenario == "AEO22") {
          electricity_EF_change <- yearly_EF_change$`Yearly change`[which(yearly_EF_change$Year == i)]/100
        }
        temp_AVERT <- AVERT_emissions_factors[which(AVERT_emissions_factors$Year == i-1),]
        temp_AVERT$Year <- i
        temp_AVERT[,4:length(colnames(temp_AVERT))] <- temp_AVERT[,4:length(colnames(temp_AVERT))]*(1+electricity_EF_change)
        AVERT_emissions_factors <- rbind(AVERT_emissions_factors, temp_AVERT)
        temp_state_emission_factors <- state_emission_factors[which(state_emission_factors$Year == i-1),]
        temp_state_emission_factors[,4:length(colnames(temp_state_emission_factors))] <- 0
        temp_state_emission_factors$Year <- i
        for (j in 1:dim(temp_state_emission_factors)[1]) {
           temp <- AVERT_state_allocation_factors[which(AVERT_state_allocation_factors$State == temp_state_emission_factors$State[j]), 2:length(colnames(AVERT_state_allocation_factors))]
           if (length(temp != 0)) {
            factors <- temp[which(!is.na(temp))]
            for (k in 1:length(factors)) {
               state_group <- which(AVERT_emissions_factors$Name == toupper(colnames(factors)[k]))
               temp_state_emission_factors$SO2[j] <- temp_state_emission_factors$SO2[j]+temp_AVERT$SO2_EF[state_group]*factors[k]
               temp_state_emission_factors$NOx[j] <- temp_state_emission_factors$NOx[j]+temp_AVERT$NOX_EF[state_group]*factors[k]
               temp_state_emission_factors$O3[j] <- temp_state_emission_factors$O3[j]+temp_AVERT$O3_EF[state_group]*factors[k]
               temp_state_emission_factors$CO2[j] <- temp_state_emission_factors$CO2[j]+temp_AVERT$CO2_EF[state_group]*factors[k]
               temp_state_emission_factors$PM25[j] <- temp_state_emission_factors$PM25[j]+temp_AVERT$PM25_EF[state_group]*factors[k]
               temp_state_emission_factors$VOC[j] <- temp_state_emission_factors$VOC[j]+temp_AVERT$VOC_EF[state_group]*factors[k]
               temp_state_emission_factors$NH3[j] <- temp_state_emission_factors$NH3[j]+temp_AVERT$NH3_EF[state_group]*factors[k]
            }
          }
        }
        # Average emission rates are attributed to missing states
        temp_state_emission_factors$SO2[which(temp_state_emission_factors$SO2 == 0)] <- mean(as.numeric(temp_state_emission_factors$SO2)[temp_state_emission_factors$SO2!=0])
        temp_state_emission_factors$NOx[which(temp_state_emission_factors$NOx == 0)] <- mean(as.numeric(temp_state_emission_factors$NOx)[temp_state_emission_factors$NOx!=0])
        temp_state_emission_factors$O3[which(temp_state_emission_factors$O3 == 0)] <- mean(as.numeric(temp_state_emission_factors$O3)[temp_state_emission_factors$O3!=0])
        temp_state_emission_factors$CO2[which(temp_state_emission_factors$CO2 == 0)] <- mean(as.numeric(temp_state_emission_factors$CO2)[temp_state_emission_factors$CO2!=0])
        temp_state_emission_factors$PM25[which(temp_state_emission_factors$PM25 == 0)] <- mean(as.numeric(temp_state_emission_factors$PM25)[temp_state_emission_factors$PM25!=0])
        temp_state_emission_factors$VOC[which(temp_state_emission_factors$VOC == 0)] <- mean(as.numeric(temp_state_emission_factors$VOC)[temp_state_emission_factors$VOC!=0])
        temp_state_emission_factors$NH3[which(temp_state_emission_factors$NH3 == 0)] <- mean(as.numeric(temp_state_emission_factors$NH3)[temp_state_emission_factors$NH3!=0])
        state_emission_factors <- rbind(state_emission_factors, temp_state_emission_factors)
      }
      state_emission_factors[,2:length(colnames(state_emission_factors))] <- apply(state_emission_factors[,2:length(colnames(state_emission_factors))], 2, as.numeric)
    }
    # Emission factors are combined with the electricity consumption for each state and each year
  # Remove Puerto Rico, Virgin Islands, Alaska and Hawaii
    fleet_elec_use_tot_state <- filter(fleet_elec_use_tot_state, fleet_elec_use_tot_state$State <= 60 & fleet_elec_use_tot_state$State!=2 & fleet_elec_use_tot_state$State!=15)
    fleet_emissions_elec_state <- fleet_elec_use_tot_state %>%
      add_column("SO2" = 0) %>%
      add_column("NOx" = 0) %>%
      #add_column("O3" = 0) %>%
      #add_column("CO2" = 0) %>%
      add_column("PM25" = 0) %>%
      add_column("VOC" = 0) %>%
      add_column("NH3" = 0)
    fleet_emissions_elec_state <- filter(fleet_emissions_elec_state, fleet_emissions_elec_state$Year >= first_proj_yr)
    fleet_emissions_elec_state$Unit <- "tons"
    fleet_emissions_elec_state$Value <- fleet_emissions_elec_state$Value/1e6
    for (i in 1:dim(fleet_emissions_elec_state)[1]) {
      fleet_emissions_elec_state$SO2[i] <- fleet_emissions_elec_state$Value[i]*state_emission_factors$SO2[which(state_emission_factors$State_ID == fleet_emissions_elec_state$State[i] & state_emission_factors$Year == fleet_emissions_elec_state$Year[i])][[1]]
      fleet_emissions_elec_state$NOx[i] <- fleet_emissions_elec_state$Value[i]*state_emission_factors$NOx[which(state_emission_factors$State_ID == fleet_emissions_elec_state$State[i] & state_emission_factors$Year == fleet_emissions_elec_state$Year[i])][[1]]
      #fleet_emissions_elec_state$O3[i] <- fleet_emissions_elec_state$Value[i]*state_emission_factors$O3[which(state_emission_factors$State_ID == fleet_emissions_elec_state$State[i] & state_emission_factors$Year == fleet_emissions_elec_state$Year[i])][[1]]
      #fleet_emissions_elec_state$CO2[i] <- fleet_emissions_elec_state$Value[i]*state_emission_factors$CO2[which(state_emission_factors$State_ID == fleet_emissions_elec_state$State[i] & state_emission_factors$Year == fleet_emissions_elec_state$Year[i])][[1]]
      fleet_emissions_elec_state$PM25[i] <- fleet_emissions_elec_state$Value[i]*state_emission_factors$PM25[which(state_emission_factors$State_ID == fleet_emissions_elec_state$State[i] & state_emission_factors$Year == fleet_emissions_elec_state$Year[i])][[1]]
      fleet_emissions_elec_state$VOC[i] <- fleet_emissions_elec_state$Value[i]*state_emission_factors$VOC[which(state_emission_factors$State_ID == fleet_emissions_elec_state$State[i] & state_emission_factors$Year == fleet_emissions_elec_state$Year[i])][[1]]
      fleet_emissions_elec_state$NH3[i] <- fleet_emissions_elec_state$Value[i]*state_emission_factors$NH3[which(state_emission_factors$State_ID == fleet_emissions_elec_state$State[i] & state_emission_factors$Year == fleet_emissions_elec_state$Year[i])][[1]]
    }
  } else if (electricity_scenario == "current_grid") {
    fleet_elec_use_tot_state <- filter(fleet_elec_use_tot_state, fleet_elec_use_tot_state$State <= 60 & fleet_elec_use_tot_state$State!=2 & fleet_elec_use_tot_state$State!=15)
    fleet_emissions_elec_state <- fleet_elec_use_tot_state %>%
      add_column("SO2" = 0) %>%
      add_column("NOx" = 0) %>%
      #add_column("O3" = 0) %>%
      #add_column("CO2" = 0) %>%
      add_column("PM25" = 0) %>%
      add_column("VOC" = 0) %>%
      add_column("NH3" = 0)
    fleet_emissions_elec_state <- filter(fleet_emissions_elec_state, fleet_emissions_elec_state$Year >= first_proj_yr)
    fleet_emissions_elec_state$Unit <- "tons"
    fleet_emissions_elec_state$Value <- fleet_emissions_elec_state$Value/1e6
  }
    fleet_emissions_elec_state <- select(fleet_emissions_elec_state, -c("Value"))
    write.csv(state_emission_factors, paste0(results_path, "/state_emission_factors.csv"))
    write.csv(fleet_emissions_elec_state, paste0(results_path, "/fleet_emissions_elec_state_breakdown.csv"))
  }
    return(list(fleet_emissions_elec_county = fleet_emissions_elec_county, fleet_emissions_elec_state = fleet_emissions_elec_state))
}
